services:
  proxy:

    image: traefik:latest
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./config:/etc/traefik/config
      - ./certs:/certs:ro

    networks:
      - myproxy
      

networks:
  myproxy:
    name: myproxy