global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: :80
  websecure:
    address: :443
    http:
      tls:
        certResolver: default

providers:
  docker: 
    defaultRule: "{{.name}}.localhost"
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: myproxy
  file:
    directory: "/etc/traefik/config"
    watch: true



    