http:
  middlewares:
    http-to-https:
      redirectScheme:
        scheme: https
        permanent: true

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/cert.pem
        keyFile: /certs/key.pem